### PR TITLE
Fixed visitor result type deduction at rvalue ref operators

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by Kojoley** [comment]
It looks like I found another bug, but I do not have GCC 4.6 to investigate it. Should I blacklist it from running the test?

**Comment by apolukhin** [comment]
Just blacklist it along with GCC 4.7

GCC < 4.8 have wired C++11 support for rvalues. IMO it should be disabled in Boost.Config

**Comment by Kojoley** [comment]
I've changed macro to `BOOST_NO_CXX11_REF_QUALIFIERS` and it solved the issue as `boost::apply_visitor` calls variant type `apply_visitor` method which relies on ref qualifiers to detect moving.

**Comment by apolukhin** [comment]
Many thanks for the PR!

**Pull request merged**
