### PR TITLE
Fixed missing noreturn

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by apolukhin** [comment]
Looks like all the `forced_return()` in that header must be marked with `BOOST_NORETURN`.

It also looks like there's a misleading documentation for `BOOST_NORETURN` macro (`BOOST_NORETURN` is applicable to any function, not just to functions that return `void`)

**Comment by Kojoley** [comment]
I have tried it and then clang warns about `return` statement in `noreturn` function.

**Comment by apolukhin** [comment]
Thanks for the patch!

**Comment by Kojoley** [comment]
I've spotted opposite warning in the http://www.boost.org/development/tests/develop/output/GLIS-homo-impi-spirit-intel-linux-warnings.html#qi_utree1-p3 build. It seems related to the PR.
```
../boost/variant/detail/forced_return.hpp(50): warning #1628: function declared with "noreturn" does return
```
I think because of `--bjam-options=release` flag `BOOST_ASSERT` becomes nothing (if I correctly understand the doc http://www.boost.org/doc/libs/1_61_0/libs/assert/assert.html). Maybe it is better to change it to `BOOST_VERIFY` or `std::terminate`?

**Comment by apolukhin** [comment]
std::terminate seems right. But it's better not to change assert, but rather add std::terminate after the assert.

**Comment by apolukhin** [comment]
But I'm afraid that it will produce some other warnings. Could you please check the solution with std::terminate after assert?

**Comment by Kojoley** [comment]
Ok. Will be soon with results.

**Comment by Kojoley** [comment]
I can confirm that adding `std::terminate` at the end of the function (after the `BOOST_ASSERT`) solves the problem and do not produce other warnings. Checked with Clang (`-Wmissing-noreturn` flag) and `variant=debug,release`. Should I open a PR or you will it yourself?

**Comment by Kojoley** [comment]
`-Wall -Wextra -Wmissing-noreturn` is OK too, got only this:
```
auto_visitors.cpp:154:37: warning: unused parameter 'val' [-Wunused-parameter]
    const char* operator()(const T& val) const {
                                    ^
auto_visitors.cpp:159:38: warning: unused parameter 'v1' [-Wunused-parameter]
    const char* operator()(const T1& v1, const T2& v2) const {
                                     ^
auto_visitors.cpp:159:52: warning: unused parameter 'v2' [-Wunused-parameter]
    const char* operator()(const T1& v1, const T2& v2) const {
                                                   ^
auto_visitors.cpp:165:38: warning: unused parameter 'v1' [-Wunused-parameter]
    const char* operator()(const T1& v1, const T2& v2, const T3& v3) const {
                                     ^
auto_visitors.cpp:165:52: warning: unused parameter 'v2' [-Wunused-parameter]
    const char* operator()(const T1& v1, const T2& v2, const T3& v3) const {
                                                   ^
auto_visitors.cpp:165:66: warning: unused parameter 'v3' [-Wunused-parameter]
    const char* operator()(const T1& v1, const T2& v2, const T3& v3) const {
                                                                 ^
6 warnings generated.
```

**Pull request merged**
